config/routes.rb
Rails.application.routes.draw do

  root "vehicles#index"


  resources :vehicles do
    resources :trips
  end

  # get "/vehicles/:vehicle_id/trips/", to: "trips#show", as: "vehicle_trip_path"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :vehicle

#   validates :trip_number, presence: true
#   validates :distance, presence: true
#   validates :fuel_consumption, presence: true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord

    has_many :trips, dependent: :destroy

    validates :vehicle_number, presence: true
    validates :vehicle_type, presence: true
    validates :vehicle_model, presence: true
    validates :vehicle_color, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
    def create
        @vehicle = Vehicle.find(params[:vehicle_id])
        @trip = @vehicle.trips.create(trip_params)
        redirect_to vehicle_path(@vehicle)
      end

      def new
        @vehicle = Vehicle.find(params[:vehicle_id])
        @trip=Trip.new
        # redirect_to new_vehicle_trip_path(@vehicle)
      end

      def show
        @vehicle = Vehicle.find(params[:vehicle_id])
        @trip=@vehicle.trips.find(params[:id])
        # redirect_to vehicle_trip_path(@trip)
      end

      def edit
        binding.pry
        @vehicle = Vehicle.find(params[:vehicle_id])
        @trip=@vehicle.trips.find(params[:id])
        # redirect_to edit_vehicle_trip_path(@vehicle)
      end
  
      def destroy
        @vehicle = Vehicle.find(params[:vehicle_id])
        @trip = @vehicle.trips.find(params[:id])
        @trip.destroy
        redirect_to vehicle_path(@vehicle), status: 303
      end
    
      private
        def trip_params
          params.require(:trip).permit(:trip_number, :distance, :fuel_consumption)
        end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def index
    @vehicles=Vehicle.all
  end

  def show
    @vehicle=Vehicle.find(params[:id])
  end

  def new
    @vehicle=Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)

    if @vehicle.save
      redirect_to @vehicle
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  def update
    @vehicle = Vehicle.find(params[:id])

    if @vehicle.update(vehicle_params)
      redirect_to @vehicle
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def vehicle_params
      params.require(:vehicle).permit(:vehicle_number, :vehicle_type, :vehicle_model, :vehicle_color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vehicles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trips/_form.html.erb
<%= form_with model: [ @vehicle, @vehicle.trips.build ] do |form| %>
    <p>
    <%= form.label :trip_name %><br>
    <%= form.text_field :trip_name %>
  </p>
  
  <p>
    <%= form.label :trip_number %><br>
    <%= form.text_field :trip_number %>
  </p>

  <p>
    <%= form.label :distance %><br>
    <%= form.text_area :distance %>
  </p>

   <p>
    <%= form.label :fuel_consumption %><br>
    <%= form.text_area :fuel_consumption %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/trips/_new.html.erb
<h2>Add a trip:</h2>

<%= render 'trips/form', trip: @trip %>

app/views/trips/_trip.html.erb
<p>
<%= link_to trip.trip_name,vehicle_trip_path(trip)%>
</p>








<!--
<p>
<strong>trip_number:</strong>
<%= trip.trip_number %>
</p>

<p>
<strong>distance:</strong>
<%= trip.distance %>
</p>

<p>
<strong>fuel_consumption:</strong>
<%= trip.fuel_consumption %>
</p>


<p>
<%# <%= link_to "Add Trip", new_vehicle_trip_path(@trip)%> 

<%= link_to "Edit Trip  ", edit_vehicle_trip_path(@vehicle)%>

<%= link_to "  Destroy trip", [trip.vehicle, trip], data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
        } %>
</p>
-->

app/views/trips/edit.html.erb
<h1>Edit Trip</h1>

<%= render "form", trip: @trip %>

app/views/trips/show.html.erb
<p><b>Trip name:</b><%= @trip.trip_name %></p>

<p><b>Trip number:</b><%= @trip.trip_number %></p>

<p><b>Distance:</b><%= @trip.distance %></p>

<p><b>Fuel Consumption:</b><%= @trip.fuel_consumption %></p>




<ul>
    <li><%= link_to "Edit", edit_vehicle_trip_path(@trip)%></li>
    
    <li><%= link_to "Destroy", vehicle_trip_path(@trip), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>

</ul>


app/views/vehicles/_form.html.erb
<%= form_with model: @vehicle do |form| %>
  <div>
  <%= form.label :vehicle_number %><br>
  <%= form.text_field :vehicle_number %>
  <% @vehicle.errors.full_messages_for(:vehicle_number).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>

  <div>
  <%= form.label :vehicle_type %><br>
  <%= form.text_area :vehicle_type %><br>
  <% @vehicle.errors.full_messages_for(:vehicle_type).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>

  <div>
  <%= form.label :vehicle_model %><br>
  <%= form.text_area :vehicle_model %><br>
  <% @vehicle.errors.full_messages_for(:vehicle_model).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>

  <div>
  <%= form.label :vehicle_color %><br>
  <%= form.text_area :vehicle_color %><br>
  <% @vehicle.errors.full_messages_for(:vehicle_color).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>

  <div>
  <%= form.submit %>
  </div>


<% end %>

app/views/vehicles/edit.html.erb
<h1>Edit Vehicle</h1>

<%= render "form", vehicle: @vehicle %>

app/views/vehicles/index.html.erb
<h1>Vehicles-Trips Application </h1>

<ul>
  <% @vehicles.each do |vehicle| %>
    <li>
      <%= link_to vehicle.vehicle_number, vehicle %>
    </li>
  <% end %>
</ul>

<%= link_to "New Vehicle", new_vehicle_path %>
<%# <%= link_to "New Trip", new_vehicle_trip_path %> 

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render "form", vehicle: @vehicle %>

app/views/vehicles/show.html.erb
<h1><b> Vehicle Number:</b><%= @vehicle.vehicle_number %></h1>

<p><b> Vehicle Type:</b><%= @vehicle.vehicle_type %></p>

<p><b> Vehicle Model:</b><%= @vehicle.vehicle_model %></p>

<p><b> Vehicle Color:</b><%= @vehicle.vehicle_color %></p>


<ul>
    <li><%= link_to "Edit", edit_vehicle_path(@vehicle)%></li>
    
    <li><%= link_to "Destroy", vehicle_path(@vehicle), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>

</ul>



<h2>Trips</h2>
<%= render @vehicle.trips %>

<%= link_to "Add Trip", new_vehicle_trip_path(@vehicle)%>




